#version 430

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0, rgba16f) uniform coherent image2D gridVel;
layout(binding = 1, r16f)    uniform coherent image2D gridMass;
layout(binding = 2, r16f)    uniform coherent image2D gridDivergence;

void main()
{
    ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(gridVel);
    if (gid.x <= 0 || gid.y <= 0 || gid.x >= size.x - 1 || gid.y >= size.y - 1)
        return;

    float m = imageLoad(gridMass, gid).x;
    if (m < 1e-5) {
        imageStore(gridDivergence, gid, vec4(0.0));
        return;
    }

    vec2 vL = imageLoad(gridVel, gid + ivec2(-1, 0)).xy;
    vec2 vR = imageLoad(gridVel, gid + ivec2(1, 0)).xy;
    vec2 vB = imageLoad(gridVel, gid + ivec2(0, -1)).xy;
    vec2 vT = imageLoad(gridVel, gid + ivec2(0, 1)).xy;

    float div = (vR.x - vL.x + vT.y - vB.y) * 0.5;
    imageStore(gridDivergence, gid, vec4(div));
}
