#version 430

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0, r16f)    uniform coherent image2D pressureIn;
layout(binding = 1, r16f)    uniform coherent image2D divergence;
layout(binding = 2, r16f)    uniform coherent image2D pressureOut;

void main()
{
    ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(pressureIn);
    if (gid.x <= 0 || gid.y <= 0 || gid.x >= size.x - 1 || gid.y >= size.y - 1)
        return;

    float pL = imageLoad(pressureIn, gid + ivec2(-1, 0)).x;
    float pR = imageLoad(pressureIn, gid + ivec2(1, 0)).x;
    float pB = imageLoad(pressureIn, gid + ivec2(0, -1)).x;
    float pT = imageLoad(pressureIn, gid + ivec2(0, 1)).x;

    float div = imageLoad(divergence, gid).x;
    float p = (pL + pR + pB + pT - div) * 0.25;
    imageStore(pressureOut, gid, vec4(p));
}
